# Generated by Django 5.2.11 on 2026-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('like', 'Like'), ('favorite', 'Favorite'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('purchase', 'Purchase'), ('ar_session_start', 'AR Session Start'), ('ar_session_end', 'AR Session End'), ('ar_screenshot', 'AR Screenshot')], max_length=50),
        ),
    ]
