# Generated by Django 5.2.11 on 2026-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='needs_rebuild',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
